### PR TITLE
fix: PatchByFullSymbolName panic when `Restore` from unpatch

### PR DESCRIPTION
**Pull request by u2386**
#15

### CODE REVIEW

**Comment by Mutated1994** [comment]
As far as my concern, the restore method that is redundant, but I'd like to try to fix it (please wait a moment).

**Comment by Mutated1994** [comment]
This is my way #17 @u2386

**Comment by u2386** [comment]
> the restore method that is redundant

Restore is quite useful, e.g

```golang
var guard *supermonkey.PatchGuard
guard = supermonkey.PatchByFullSymbolName(time.Now, func() time.Time {
	guard.Unpatch()
	defer guard.Restore()

	actual := time.Now()
	manipulated := actual.Add(time.Hour)
	return manipulated
})
```

**Comment by cch123** [comment]
> > the restore method that is redundant
> 
> Restore is quite useful, e.g
> 
> ```go
> var guard *supermonkey.PatchGuard
> guard = supermonkey.PatchByFullSymbolName(time.Now, func() time.Time {
> 	guard.Unpatch()
> 	defer guard.Restore()
> 
> 	actual := time.Now()
> 	manipulated := actual.Add(time.Hour)
> 	return manipulated
> })
> ```

@Mutated1994

**Comment by Mutated1994** [comment]
> > > the restore method that is redundant
> > 
> > 
> > Restore is quite useful, e.g
> > ```go
> > var guard *supermonkey.PatchGuard
> > guard = supermonkey.PatchByFullSymbolName(time.Now, func() time.Time {
> > 	guard.Unpatch()
> > 	defer guard.Restore()
> > 
> > 	actual := time.Now()
> > 	manipulated := actual.Add(time.Hour)
> > 	return manipulated
> > })
> > ```
> 
> @Mutated1994

Sorry, I'm late.
@u2386 Dude, I've changed my mind. You are right in your case!
@u2386 @cch123 I've fix this issue. #17

**Comment by cch123** [comment]
https://github.com/cch123/supermonkey/pull/17 is merged, so close this ~

**Pull request closed without merging**
